"""Headline comparison figure -- proposed method versus all baselines (bar chart).

This script consumes the deterministic data table produced by
``learned_residual.py`` (``generated_data/learned_residual_sizes.csv``) and renders
the single headline display item of the manuscript: a grouped bar chart of the
final global spectral-norm error of every method at the largest held-out transfer
size, together with the error-reduction factor of the proposed learned correction
over the uncorrected baseline across all transfer sizes.

It introduces no new numerics -- every value is read back from the verified CSV --
so the headline figure is a deterministic function of the learned-residual data and
is regenerated byte-for-byte on every run.

Output: figures/fig6_headline_improvement.{pdf,png}.
"""
from __future__ import annotations

import argparse

import numpy as np
import pandas as pd

from common import DATA_DIR, PALETTE, line_plot_style, panel_label, plt, save_figure

OUT_FIGURE = "fig6_headline_improvement.pdf"

# (column prefix, legend label, colour) for every method shown against the proposal.
METHODS = [
    ("baseline_error", "uncorrected Strang", PALETTE[0]),
    ("bch_leading_error", "leading-order BCH", PALETTE[1]),
    ("learned_free_error", "learned residual (ours)", PALETTE[2]),
    ("oracle_local_error", r"exact weight-$\leq$3 oracle", PALETTE[3]),
]


def make_plot(df: pd.DataFrame) -> None:
    df = df.sort_values("n_qubits")
    largest = df.iloc[-1]
    n_max = int(largest["n_qubits"])

    fig, (ax_a, ax_b) = plt.subplots(1, 2, figsize=(10.2, 4.4))

    # (a) Final error of every method at the largest transfer size (bar, log y).
    labels = [m[1] for m in METHODS]
    values = np.array([float(largest[f"{m[0]}_mean"]) for m in METHODS])
    errors = np.array([float(largest.get(f"{m[0]}_std", 0.0)) for m in METHODS])
    colors = [m[2] for m in METHODS]
    xs = np.arange(len(METHODS))
    ax_a.bar(xs, values, yerr=errors, color=colors, width=0.66, capsize=3, error_kw={"elinewidth": 1.0})
    ax_a.set_yscale("log")
    ax_a.set_xticks(xs)
    ax_a.set_xticklabels(labels, rotation=20, ha="right", fontsize=8.5)
    ax_a.set_ylabel("global spectral-norm error")
    ax_a.set_title(f"Final error at held-out $n={n_max}$")
    ax_a.grid(alpha=0.25, axis="y")
    panel_label(ax_a, "a")

    # (b) Error-reduction factor of the proposed correction over the baseline,
    #     across all transfer sizes (bar).
    n_vals = df["n_qubits"].to_numpy()
    reduction = (df["baseline_error_mean"] / df["learned_free_error_mean"]).to_numpy()
    ax_b.bar(n_vals, reduction, color=PALETTE[2], width=0.62)
    ax_b.axhline(1.0, linestyle="--", color=PALETTE[0], linewidth=1.0)
    ax_b.set_xlabel("chain length $n$")
    ax_b.set_ylabel(r"reduction factor $\epsilon_{\mathrm{Strang}}/\epsilon_{\mathrm{learned}}$")
    ax_b.set_title("Improvement of proposed correction")
    ax_b.set_xticks(n_vals)
    ax_b.grid(alpha=0.25, axis="y")
    panel_label(ax_b, "b")

    fig.tight_layout(pad=1.2)
    save_figure(fig, OUT_FIGURE)


def main(force: bool = False) -> bool:
    csv_path = DATA_DIR / "learned_residual_sizes.csv"
    if not csv_path.exists():
        print(f"skipping headline figure: {csv_path.name} not found (run learned_residual first)")
        return False
    df = pd.read_csv(csv_path)
    make_plot(df)
    return True


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--force", action="store_true")
    args = parser.parse_args()
    main(force=args.force)
